name: Merge from Other Repository

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use version 3 of actions/checkout
        with:
          token: ${{ secrets.COBA }}  # Add the token here to authenticate the checkout

      - name: Set up Git
        run: |
          git config --global user.email "zainrizqulloh@gmail.com"
          git config --global user.name "MZAINR"
          git config --global credential.username "MZAINR"

      - name: Print Remote Info
        run: git ls-remote origin

      - name: Merge from Other Repository
        run: |
          git remote add other_repo https://github.com/gilangherdiansyah80/Project_Capstone_EcoSync.git
          git fetch other_repo
          git checkout -b merge_branch other_repo/main
          git checkout main
          git merge --allow-unrelated-histories merge_branch
          git push origin main
